# .github/workflows/test1.yml
name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tuist
      	run: curl -Ls https://install.tuist.io | bash
      - name: Fetch Swift Packages
        run: tuist fetch
      - name: Generate Project
        run: tuist generate
      - name: Build and Test
        run:  xcodebuild clean test -workspace ActionWorkspace.xcworkspace -scheme ActionWorkspace-Workspace -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=latest'
