# .github/workflows/my-project.yml
name: My project

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'test'
          arguments: ''